//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5_StokTakip.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class TBLMUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMUSTERILER()
        {
            this.TBLSATISLAR = new HashSet<TBLSATISLAR>();
        }
    
        public int MUSTERIID { get; set; }
		[Required(ErrorMessage ="Müþteri adý boþ býrakýlamaz!")]
		[StringLength(50, ErrorMessage ="Müþteri adý 50 karakterden uzun olamaz!")]
        public string MUSTERIAD { get; set; }
		[Required(ErrorMessage = "Müþteri soyadý boþ býrakýlamaz!")]
		[StringLength(50,ErrorMessage ="Müþteri soyadý 50 karakterden uzun olamaz!")]
		public string MUSTERISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSATISLAR> TBLSATISLAR { get; set; }
    }
}
